name: data-source
language: python
variables:
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write into
    defaultValue: 2d-vector
    required: true
  - name: ms_to_sleep
    inputType: FreeText
    multiline: false
    defaultValue: 500
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
